#!/bin/sh

local hotst_proxy_protocol=$1
local host_proxy_port=$2
local host_ip=$3

if [ ! -n "$1" ]; then local hotst_proxy_protocol="socks5"; fi
if [ ! -n "$2" ]; then local host_proxy_port="7891"; fi
if [ ! -n "$3" ]; then local host_ip=$(cat /etc/resolv.conf | grep -oP '(?<=nameserver\ ).*'); fi

if command -v proxychains4 >/dev/null 2>&1; then 
    echo "dynamic_chain" > /etc/proxychains.conf
    echo "chain_len = 1" >> /etc/proxychains.conf
    echo "proxy_dns" >> /etc/proxychains.conf
    echo "remote_dns_subnet 224" >> /etc/proxychains.conf
    echo "tcp_read_time_out 15000" >> /etc/proxychains.conf
    echo "tcp_connect_time_out 8000" >> /etc/proxychains.conf
    echo "[ProxyList]" >> /etc/proxychains.conf
    echo "$hotst_proxy_protocol  $host_ip $host_proxy_port" >> /etc/proxychains.conf

    alias proxy="export IS_ROOT_SHELL=yes && proxychains4 -q"
else
    echo "需要 proxychains4 可尝试输入 [installProxychains] 进行安装"
fi

function installProxychains
{
    sudo echo "\n开始安装.." \
    && cd /tmp \
    && git clone https://github.com/rofl0r/proxychains-ng.git \
    && cd proxychains-ng \
    && sudo ./configure \
    && sudo make && sudo make install \
    && sudo touch /etc/proxychains.conf \
    && sudo chmod 777 /etc/proxychains.conf \
    && echo "安装成功"
}
