#!/bin/sh

function openProxy
{
    local host_ip=$(cat /etc/resolv.conf | grep -oP '(?<=nameserver\ ).*')
    local hotst_proxy_protocol=$1
    local host_proxy_port=$2

    if [ ! -n "$1" ]; then local hotst_proxy_protocol="socks5"; fi
    if [ ! -n "$2" ]; then local host_proxy_port="7891"; fi

    export all_proxy=$hotst_proxy_protocol://$host_ip:$host_proxy_port
    export ftp_proxy=$hotst_proxy_protocol://$host_ip:$host_proxy_port
    export http_proxy=$hotst_proxy_protocol://$host_ip:$host_proxy_port
    export https_proxy=$hotst_proxy_protocol://$host_ip:$host_proxy_port
}

function closeProxy
{
    unset all_proxy
    unset ftp_proxy
    unset http_proxy
    unset https_proxy
}
